### PR TITLE
Pull oscam from the new git repo

### LINKED ISSUE #42: [FEAT] switch from old SVN to git
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Change the Dockerfile to use the new git repository: https://git.streamboard.tv/common/oscam

### Reason for change

The oscam developer switches from svn to git.

### Proposed code change

_No response_

### PR DESCRIPTION
**Pull request by aptalca**
closes #42

### CODE REVIEW

**Review by thespad — COMMENTED** [review]
Can presumably remove the `subversion` package too?

**Comment by opensauce00** [comment]
You will need to install git and clone the repo too because of [this commit](https://git.streamboard.tv/common/oscam/-/commit/7c3b3357ece53624a64318f25a879431eb68060a).

**Comment by aptalca** [comment]
> Can presumably remove the `subversion` package too?

Done

**Comment by aptalca** [comment]
> You will need to install git and clone the repo too because of [this commit](https://git.streamboard.tv/common/oscam/-/commit/7c3b3357ece53624a64318f25a879431eb68060a).

No need

**Comment by opensauce00** [comment]
> > You will need to install git and clone the repo too because of [this commit](https://git.streamboard.tv/common/oscam/-/commit/7c3b3357ece53624a64318f25a879431eb68060a).
> 
> No need

It builds successfully but doesn't show the git sha on oscam as intended. Here is a line of the build log to compare.

```OSCam ver: 1.30 rev: 11769 sha:  target: x86_64-alpine-linux-musl```

instead of

```OSCam ver: 1.30 rev: 11769 sha: a1cd3e66 target: x86_64-linux-gnu```

**Comment by aptalca** [comment]
https://git.streamboard.tv/common/oscam/-/commit/cb2acea6934c1a05cc2aa12e32be05cdd2aeb614
Third bullet

**Review by thespad — APPROVED** [review]

**Pull request merged**
